# LAB 1 OF Machine Learning
# Numpy Practice

## by sarvesh kumar sharma
## Section-A
## Roll number 50

In [1]:
import numpy as np

#### Q1. Write a Numpy program to compute Multiplication of two Matrices.

In [2]:
a=np.array([[5,8,9],[1,2,3],[3,7,4]])
a

array([[5, 8, 9],
       [1, 2, 3],
       [3, 7, 4]])

In [3]:
b=np.array([[9,1,13],[7,6,5],[18,11,5]])
b

array([[ 9,  1, 13],
       [ 7,  6,  5],
       [18, 11,  5]])

In [4]:
print(a.dot(b))

[[263 152 150]
 [ 77  46  38]
 [148  89  94]]


#### Q2 Write a numpy program to Compute Outer product of two given vectors.

In [5]:
print(np.outer(a,b))

[[ 45   5  65  35  30  25  90  55  25]
 [ 72   8 104  56  48  40 144  88  40]
 [ 81   9 117  63  54  45 162  99  45]
 [  9   1  13   7   6   5  18  11   5]
 [ 18   2  26  14  12  10  36  22  10]
 [ 27   3  39  21  18  15  54  33  15]
 [ 27   3  39  21  18  15  54  33  15]
 [ 63   7  91  49  42  35 126  77  35]
 [ 36   4  52  28  24  20  72  44  20]]


#### Q3- Write a NumPy program to compute the cross product of two given vectors.

In [6]:
print(np.cross(a,b))

[[ 95  16 -67]
 [ -8  16  -8]
 [ -9  57 -93]]


#### 4. Write a NumPy program to compute the determinant of a given square array.

In [7]:
print(np.linalg.det(a))

-15.999999999999991


#### 5. Write a NumPy program to evaluate Einstein's summation convention of two given multidimensional arrays. 

In [8]:
print(np.einsum("pq,qr",a,b))

[[263 152 150]
 [ 77  46  38]
 [148  89  94]]


#### 6. Write a NumPy program to compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension.

In [9]:
x=np.array([2,3,4])
y=np.array([7,8,9])
#print 
print(np.inner(x,y))

74


In [10]:
print(np.inner(a,b))

[[170 128 223]
 [ 50  34  55]
 [ 86  83 151]]


#### 7. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array. 

In [13]:
value,vector=np.linalg.eig(b)
print("value",value)
print("vector",vector)

value [25.64139777 -8.32551659  2.68411881]
vector [[-0.5815023  -0.60064518  0.52959826]
 [-0.38911607  0.01449123 -0.82581921]
 [-0.71445347  0.79938437 -0.19377388]]


#### 8. Write a NumPy program to compute the Kronecker product of two given mulitdimension arrays. 

In [14]:
print(np.kron(a,b))

[[ 45   5  65  72   8 104  81   9 117]
 [ 35  30  25  56  48  40  63  54  45]
 [ 90  55  25 144  88  40 162  99  45]
 [  9   1  13  18   2  26  27   3  39]
 [  7   6   5  14  12  10  21  18  15]
 [ 18  11   5  36  22  10  54  33  15]
 [ 27   3  39  63   7  91  36   4  52]
 [ 21  18  15  49  42  35  28  24  20]
 [ 54  33  15 126  77  35  72  44  20]]


#### 9. Write a NumPy program to compute the condition number of a given matrix. 

In [15]:
print(np.linalg.cond(a))

36.530329474288926


#### 10. Write a NumPy program to find a matrix or vector norm. 

In [16]:
print(np.linalg.norm(b))

28.827070610799147


#### 11. Write a NumPy program to compute the determinant of an array. 

In [17]:
print(np.linalg.det(a))

-15.999999999999991


#### 12. Write a NumPy program to compute the inverse of a given matrix. 

In [18]:
print(np.linalg.inv(b))

[[ 0.04363002 -0.2408377   0.12739965]
 [-0.09598604  0.32984293 -0.08027923]
 [ 0.05410122  0.14136126 -0.08202443]]


#### 13. Write a NumPy program to calculate the QR decomposition of a given matrix.

In [19]:
print(np.linalg.qr(a))

(array([[-0.84515425,  0.52704628,  0.08908708],
       [-0.16903085, -0.10540926, -0.97995789],
       [-0.50709255, -0.84327404,  0.17817416]]), array([[ -5.91607978, -10.64894361, -10.14185106],
       [  0.        ,  -1.8973666 ,   1.05409255],
       [  0.        ,   0.        ,  -1.42539329]]))


#### 14. Write a NumPy program to compute the condition number of a given matrix.

In [20]:
print(np.linalg.cond(b))

12.616439724455784


#### 15. Write a NumPy program to compute the sum of the diagonal element of a given array. 

In [21]:
print(np.trace(a))

11


## Thank you